### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by scottrobertson** [TryGhost/node-sqlite3#1516]
Any ideas? Tried lots of things over the last day or so.

Machine: MacBook Pro M1 Max
OS: MacOS 12
Node: v14.18.1
Yarn: v1.22.17

```
error ~/code/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: ~/code/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.18.1 | darwin | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "~/code/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@14.18.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.18.1 | darwin | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.18.1 | darwin | arm64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /opt/homebrew/opt/python@3.9/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:383:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
gyp ERR! System Darwin 21.2.0
gyp ERR! command "/Users/user/.nvm/versions/node/v14.18.1/bin/node" "~/code/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=~/code/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=~/code/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3" "--python=/opt/homebrew/opt/python@3.9/bin/python3"
gyp ERR! cwd ~/code/node_modules/sqlite3
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/user/.nvm/versions/node/v14.18.1/bin/node ~/code/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=~/code/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=~/code/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=/opt/homebrew/opt/python@3.9/bin/python3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (~/code/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Darwin 21.2.0
node-pre-gyp ERR! command "/Users/user/.nvm/versions/node/v14.18.1/bin/node" "~/code/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd ~/code/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.18.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
```

**Comment by systemlevel** [comment]
Same thing on M1 Max

**Comment by jtosey** [comment]
Same error, on same config:

Machine: MacBook Pro M1 Max
OS: MacOS 12
Node: v14.18.1
Yarn: v1.22.17

**Comment by XPalpatineX** [comment]
Same error on M1

**Comment by GeorgeChatzigiannis** [comment]
Is there any solution for this?

**Comment by jtosey** [comment]
I discovered this problem only happens for me when using yarn. If you use `npm install` rather than `yarn install`, it worked fine for me. This package was authored with `npm` tooling, and it seems that `yarn` is not entirely backward compatible.  It is somehow affecting the environment differently in a way that caused `node-gyp` to use `python 3` rather than `python 2.7`.

**Comment by scottrobertson** [comment]
I was able to get things running by using:

```
export npm_config_python=/usr/bin/python2.7
```

Before running `yarn`

Not the best fix, but it works for now.

**Comment by tianon** [comment]
I think this is fixed by https://github.com/mapbox/node-sqlite3/pull/1441, however it's not in a release yet. :disappointed:

**Comment by Piumal1999** [comment]
> I was able to get things running by using:
> 
> ```
> export npm_config_python=/usr/bin/python2.7
> ```
> 
> Before running `yarn`
> 
> Not the best fix, but it works for now.

This worked. Thank you very much. However, the issue is still there

**Comment by daniellockyer** [comment]
This should be fixed in `sqlite3` v5.0.3 - let me know if you still experience issues 🙂
